#!/bin/sh

vdiff () {
    if [ "${#}" -ne 2 ] ; then
        echo "vdiff requires two arguments"
        echo "  comparing dirs:  vdiff dir_a dir_b"
        echo "  comparing files: vdiff file_a file_b"
        return 1
    fi

    local left="${1}"
    local right="${2}"

    if [ -d "${left}" ] && [ -d "${right}" ]; then
        vim +"DirDiff ${left} ${right}"
    else
        vim -d "${left}" "${right}"
    fi
}

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# miscellaneous
#alias sudo='doas'
alias \
	c='clear' \
	mpd='mpd ~/.config/mpd/mpd.conf' \
	groff='/usr/local/Cellar/groff/1.22.4_1/bin/groff'

# Utilities
alias \
	u='app-cleaner.sh' \
	wtr='curl wttr.in' \
	wpass='wifi-password' \
	myip='curl ifconfig.co' \
	spd="speedtest"

# Navigation
alias \
	..='cd ..' \
	...='cd ../..' \
	.3='cd ../../..' \
	.4='cd ../../../..' \
	.5='cd ../../../../..'

# brew
# update all brew pkgs
alias bsyu='cd $HOME/.config/brew; brew update -v;\
        brew upgrade -v --display-times --greedy;\
        brew bundle -vf --all --describe;\
		brew cu -ayv --cleanup --include-mas; cd; bfsyu; bclean'
# create brewfile in $HOME/.config/brew
alias bfcrt='cd $HOME/.config/brew && brew bundle dump --describe && cd'
# update brewfile
alias bfsyu='cd $HOME/.config/brew; brew bundle dump -vf --all --describe;\
        brew bundle cleanup -vf --describe; cd'
# remove orphaned packages
alias bclean='brew autoremove && brew cleanup && brew doctor -v'
# list dependencies
alias bdepls='brew deps -n --tree --installed --annotate'
alias bls='brew list -1 --full-name'
alias boutdtd='brew outdated -v'

# Change "ls" to "eza"
alias \
	ls='eza -al --color=always --group-directories-first --git' \
	la='eza -a --color=always --group-directories-first --git' \
	ll='eza -l --color=always --group-directories-first --git' \
	lt='eza -aT --color=always --group-directories-first --git' \
	l.='eza -a | egrep "^\."'

# Colorize commands when possible.
alias diff="diff --color=auto" \

# Colorize grep output (good for log files)
alias \
	grep='grep --color=auto' \
	egrep='egrep --color=auto' \
	fgrep='fgrep --color=auto'

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -iv" \
	bc="bc -ql" \
	mkd="mkdir -pv" \
	yt="yt-dlp --add-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ffmpeg="ffmpeg -hide_banner"

# These common commands are just too long! Abbreviate them.
alias \
	ka='killall' \
	g='git' \
	sdn='sudo shutdown -h now' \
	e='$EDITOR' \
	v='$EDITOR' \
	b='brew' \
	z='xpdf' \
	nb='newsboat' \
  tasktui="taskwarrior-tui" \
	scim='sc-im' \
	ytdlp='yt-dlp' \
	sdcv='sdcvrun' \
	YT="youtube-viewer" \
	pf="fzf --preview='less {}' --bind shift-up:preview-page-up,shift-down:preview-page-down"
  pdfcat=""

# Adding flags
alias \
	df='df -h' \
	vifm='./.config/vifm/scripts/vifmrun' \
	ncmpcpp='ncmpcpp ncmpcpp_directory=$HOME/.config/ncmpcpp/' \
	mocp='mocp -M "$XDG_CONFIG_HOME"/moc -O MOCDir="$XDG_CONFIG_HOME"/moc' \
	lynx='lynx -cfg=~/.config/lynx/lynx.cfg -lss=~/.config/lynx/lynx.lss -vikeys' \
#lf='/usr/local/bin/lfrun'

# GnuPG encryption
alias gpg-check="gpg2 --keyserver-options auto-key-retrieve --verify" # verify signature for isos
alias gpg-retrieve="gpg2 --keyserver-options auto-key-retrieve --receive-keys" # receive the key of a developer

# Program Specific Aliases
# remind
alias \
	erem='nvim ~/.reminders/uni.rem'\
	wrem='rem -cl+1 -@'\
  mrem='rem -cl -@'\
	gcal='remind -cl -pp ~/.reminders/ \
		| rem2ps -l -st 55 -shd 35 -se 25 -m 30x40cm \
		| ps2pdf - > ~/.reminders/cal.pdf' \
	vcal='remind -cl -pp ~/.reminders/ \
		| rem2ps -l -st 55 -shd 35 -se 25 -m 30x40cm \
		| ps2pdf - > ~/.reminders/cal.pdf && xpdf ~/.reminders/cal.pdf' \
	urem='vim ~/.reminders/uni.rem' \
	prem='vim ~/.reminders/personal.rem'
# buku
alias bukud='bukuserver run --host 127.0.0.1 --port 5001'
# skim (pdf viewer)
alias \
	embed='skimpdf embed ' \
	unembed='skimpdf unembed '
# git
alias \
	gtg='cd $HOME/Downloads/gitthings' \
	addup='git add -u' \
	addall='git add .' \
	branch='git branch' \
	checkout='git checkout' \
	clone='git clone' \
	commit='git commit -m' \
	fetch='git fetch' \
	pull='git pull origin' \
	push='git push origin' \
	status='git status' \
	tag='git tag' \
	newtag='git tag -a'
# yt-dlp
alias \
	ydl="yt-dlp -x --audio-format mp3 -a $HOME/Downloads/ytdlp" \
	yta-best="yt-dlp --extract-audio --audio-format best " \
	ytdl-flac="yt-dlp --extract-audio --audio-format flac " \
	ytdl-m4a="yt-dlp --extract-audio --audio-format m4a " \
	ytdl-mp3="yt-dlp --extract-audio --audio-format mp3 " \
	yta-opus="yt-dlp --extract-audio --audio-format opus " \
	yta-wav="yt-dlp --extract-audio --audio-format wav " \
	ytv-best="yt-dlp -f bestvideo+bestaudio "

# Switch between shells
alias \
	tobash="sudo chsh $USER -s /bin/bash && echo 'Now log out.'" \
	tozsh="sudo chsh $USER -s /bin/zsh && echo 'Now log out.'"

# Terminal rickroll
alias rr='curl -s -L https://raw.githubusercontent.com/keroserene/rickrollrc/master/roll.sh | bash'

# Wget Command to Retrieve Whole Websites
alias wsa='wget --mirror --convert-links --page-requisites --no-parent -P $HOME/Documents/website-archives/'

# Generate and deploy personal website
alias \
	gw='cd ~/.blog/SteveSite/ && rm -f ~/.blog/SteveSite/dst/.files && ~/.blog/SteveSite/bin/ssg6 src dst "Steve Blog" "https://hghann.github.io/" && rsync -av ~/.blog/SteveSite/dst/ ~/.blog/SteveSite/'
	dw='cd ~/.blog/SteveSite/ && rm -f ~/.blog/SteveSite/dst/.files && ~/.blog/SteveSite/bin/ssg6 src dst "hghanns Blog" "https://hghann.github.io/" && rsync -av ~/.blog/SteveSite/dst/ ~/.blog/SteveSite/ && git add . && git commit -m "minor edits" && git push -u origin master'
