#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# ex - archive extractor
# usage: ex <file>
ex ()
{
  if [ -f $1 ] ; then
    case $1 in
      *.tar.bz2)   tar xjf $1   ;;
      *.tar.gz)    tar xzf $1   ;;
      *.tar.xz)    tar xJf $1   ;;
      *.bz2)       bunzip2 $1   ;;
      *.rar)       unrar x $1     ;;
      *.gz)        gunzip $1    ;;
      *.tar)       tar xf $1    ;;
      *.tbz2)      tar xjf $1   ;;
      *.tgz)       tar xzf $1   ;;
      *.zip)       unzip $1     ;;
      *.Z)         uncompress $1;;
      *.7z)        7z x $1      ;;
      *)           echo "'$1' cannot be extracted via ex()" ;;
    esac
  else
    echo "'$1' is not a valid file"
  fi
}

# miscellaneous
#alias sudo='doas'
alias \
	c='clear' \
    mpd='mpd ~/.config/mpd/mpd.conf' \
	groff='/usr/local/Cellar/groff/1.22.4_1/bin/groff'

# Utilities
alias \
	u='app-cleaner.sh' \
	wtr='curl wttr.in' \
	wpass='wifi-password' \
	myip='curl ifconfig.co' \
	spd="speedtest"

# Navigation
alias \
	..='cd ..' \
	...='cd ../..' \
	.3='cd ../../..' \
	.4='cd ../../../..' \
	.5='cd ../../../../..'

# brew
# update all brew pkgs
alias bsyu='brew update -v; brew upgrade -v --display-times;\
		cd $HOME/.config/brew; brew bundle -v;\
		brew cu -afyv; cd; brew doctor -v'
# create brewfile in $HOME/.config/brew
alias bfcrt='cd $HOME/.config/brew && brew bundle dump --describe && cd'
# update brewfile
alias bfsyu='cd $HOME/.config/brew && brew bundle dump --force --describe && cd'
# remove orphaned packages
alias bclean='brew autoremove && brew cleanup && brew doctor -v'
# list dependencies
alias bdepls='brew deps -n --tree --installed --annotate'
alias bdepg='brew deps -n --graph --dot --installed --annotate'
alias bls='brew list -1 --full-name'
alias boutdated='brew outdated -v'

# Change "ls" to "exa"
alias \
	ls='exa -al --color=always --group-directories-first --git' \
	la='exa -a --color=always --group-directories-first --git' \
	ll='exa -l --color=always --group-directories-first --git' \
	lt='exa -aT --color=always --group-directories-first --git' \
	l.='exa -a | egrep "^\."'

# Colorize commands when possible.
alias diff="diff --color=auto" \

# Colorize grep output (good for log files)
alias \
	grep='grep --color=auto' \
	egrep='egrep --color=auto' \
	fgrep='fgrep --color=auto'

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -iv" \
	bc="bc -ql" \
	mkd="mkdir -pv" \
	yt="yt-dlp --add-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ffmpeg="ffmpeg -hide_banner"

# These common commands are just too long! Abbreviate them.
alias \
	ka='killall' \
	g='git' \
	sdn='sudo shutdown -h now' \
	e='$EDITOR' \
	v='$EDITOR' \
	b='brew' \
	z='xpdf' \
	n='newsboat' \
	scim='sc-im' \
    ytdlp='yt-dlp' \
	sdcv='sdcvrun' \
	YT="youtube-viewer" \
	trem="transmission-remote"

# Adding flags
alias \
	df='df -h' \
	vifm='./.config/vifm/scripts/vifmrun' \
	ncmpcpp='ncmpcpp ncmpcpp_directory=$HOME/.config/ncmpcpp/' \
	mocp='mocp -M "$XDG_CONFIG_HOME"/moc -O MOCDir="$XDG_CONFIG_HOME"/moc' \
	lynx='lynx -cfg=~/.config/lynx/lynx.cfg -lss=~/.config/lynx/lynx.lss -vikeys' \
#lf='/usr/local/bin/lfrun'

# GnuPG encryption
alias gpg-check="gpg2 --keyserver-options auto-key-retrieve --verify" # verify signature for isos
alias gpg-retrieve="gpg2 --keyserver-options auto-key-retrieve --receive-keys" # receive the key of a developer

# Program Specific Aliases
# remind
alias \
	erem='nvim ~/.reminders/uni.rem'\
	wrem='rem -cl+1 -@'\
	gcal='remind -cl -pp ~/.reminders/ \
		| rem2ps -l -st 55 -shd 35 -se 25 -m 30x40cm \
		| ps2pdf - > ~/.reminders/cal.pdf' \
	vcal='remind -cl -pp ~/.reminders/ \
		| rem2ps -l -st 55 -shd 35 -se 25 -m 30x40cm \
		| ps2pdf - > ~/.reminders/cal.pdf && xpdf ~/.reminders/cal.pdf' \
	urem='vim ~/.reminders/uni.rem' \
	prem='vim ~/.reminders/personal.rem'
# buku
alias bukud='bukuserver run --host 127.0.0.1 --port 5001'
# skim (pdf viewer)
alias \
	embed='skimpdf embed ' \
	unembed='skimpdf unembed '
# git
alias \
	gtg='cd $HOME/Downloads/gitthings' \
	addup='git add -u' \
	addall='git add .' \
	branch='git branch' \
	checkout='git checkout' \
	clone='git clone' \
	commit='git commit -m' \
	fetch='git fetch' \
	pull='git pull origin' \
	push='git push origin' \
	status='git status' \
	tag='git tag' \
	newtag='git tag -a'
# yt-dlp
alias \
	ydl="yt-dlp -x --audio-format mp3 -a $HOME/urls" \
	yta-best="yt-dlp --extract-audio --audio-format best " \
	yta-flac="yt-dlp --extract-audio --audio-format flac " \
	yta-m4a="yt-dlp --extract-audio --audio-format m4a " \
	yta-mp3="yt-dlp --extract-audio --audio-format mp3 " \
	yta-opus="yt-dlp --extract-audio --audio-format opus " \
	yta-vorbis="yt-dlp --extract-audio --audio-format vorbis " \
	yta-wav="yt-dlp --extract-audio --audio-format wav " \
	ytv-best="yt-dlp -f bestvideo+bestaudio "

# Switch between shells
alias \
	tobash="sudo chsh $USER -s /bin/bash && echo 'Now log out.'" \
	tozsh="sudo chsh $USER -s /bin/zsh && echo 'Now log out.'"

# Terminal rickroll
alias rr='curl -s -L https://raw.githubusercontent.com/keroserene/rickrollrc/master/roll.sh | bash'

# Wget Command to Retrieve Whole Websites
alias wsd='wget --mirror --convert-links --page-requisites --no-parent -P $HOME/Documents/website-archives/'

# Generate and deploy personal website
alias \
	gw='cd ~/.websites/hghann.github.io/ && \
		rm -f ~/.websites/hghann.github.io/dst/.files && \
		~/.websites/hghann.github.io/bin/ssg6 src dst "Steve Blog" "https://hghann.github.io/" && \
		rsync -av ~/.websites/hghann.github.io/dst/ ~/.websites/hghann.github.io/' \
	dw='cd ~/.websites/hghann.github.io/ && \
	rm -f ~/.websites/hghann.github.io/dst/.files && \
	~/.websites/hghann.github.io/bin/ssg6 src dst "hghanns Blog" "https://hghann.github.io/" && \
	rsync -av ~/.websites/hghann.github.io/dst/ ~/.websites/hghann.github.io/ && \
	git add . && git commit -m "minor edits" && git push -u origin master'
